services:
  client:
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - ./client/.env
    depends_on:
      - server

  server:
    command: npm run dev
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    working_dir: /app
    env_file:
        - ./server/.env
