version: '3.8'

services:
  postgres:
    image: postgres
    container_name: pg
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./server
    container_name: backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 5000
    volumes:
      - ./server:/app
    depends_on:
      - postgres
    ports:
      - "5000:5000"

  frontend:
    build: .
    container_name: frontend
    environment:
      VITE_API_URL: ${VITE_API_URL}
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata: