version: '3.9'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "3000:80"
    env_file:
      - ./client/.env
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env

